spring.application.name=student-course-management

spring.datasource.url=jdbc:postgresql://localhost:5433/student_course_db
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081

jwt.secret=${JWT_SECRET:change-me-local-dev-secret-at-least-32-bytes}